# Generated by Django 5.1.7 on 2026-02-05 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('priority', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('frequency_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('custom_week', 'Custom Days')], default='daily', max_length=20)),
                ('dose_per_day', models.IntegerField(default=1, help_text='How many times per day')),
                ('days_of_week', models.CharField(blank=True, help_text='Mon,Wed,Fri', max_length=50)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('duration_days', models.IntegerField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('food_timing', models.CharField(choices=[('Before Food', 'Before Food'), ('After Food', 'After Food')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='active', max_length=10)),
                ('last_taken_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='accounts.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_taken', models.BooleanField(default=False)),
                ('medicine_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='accounts.medicinetime')),
            ],
            options={
                'unique_together': {('medicine_time', 'date')},
            },
        ),
    ]
