# Generated by Django 5.2.11 on 2026-03-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_emergencycontact_id_alter_medicine_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='best_streak',
            field=models.IntegerField(default=0, help_text='Best consecutive days of perfect adherence achieved'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_streak',
            field=models.IntegerField(default=0, help_text='Current consecutive days of perfect adherence'),
        ),
    ]
