# Generated by Django 6.0.2 on 2026-03-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_best_streak_userprofile_current_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='is_reminder_enabled',
            field=models.BooleanField(default=True, help_text='Enable or disable reminders for this medicine'),
        ),
    ]
