# Generated by Django 5.2.11 on 2026-03-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='drug_classification',
            field=models.CharField(choices=[('Unclassified', 'Unclassified'), ('Antibiotic', 'Antibiotics'), ('Antidiabetic', 'Antidiabetics'), ('Antifungal', 'Antifungal'), ('Anti-Inflammatory', 'Anti-Inflammatory'), ('Antiviral', 'Antiviral'), ('Anti-Hypertensive', 'Anti-Hypertensive'), ('Tuberculosis', 'Tuberculosis'), ('Narcotic', 'Narcotic'), ('Barbiturate', 'Barbiturates'), ('Analgesic', 'Analgesic'), ('Local Anesthetic', 'Local Anesthetics'), ('Anti-Arrhythmic', 'Anti-Arrhythmics'), ('Anti-Asthmatic', 'Anti-Asthmatics'), ('Anti-Epileptic', 'Anti-Epileptics'), ('Anti-Malarial', 'Anti-Malarial'), ('Anti-Psychotic', 'Anti-Psychotic'), ('Diuretic', 'Diuretics'), ('UTI Drug', 'UTI Drugs'), ('Proton Pump Inhibitor', 'Proton Pump Inhibitors'), ('Anti-Emetic', 'Anti-Emetic')], default='Unclassified', help_text='Drug classification category', max_length=30),
        ),
    ]
