# Generated by Django 5.2.11 on 2026-03-03 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_medicine_drug_classification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='next_due_time',
            field=models.TimeField(blank=True, help_text='Next scheduled time to take this medicine', null=True),
        ),
        migrations.CreateModel(
            name='MedicineDoseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.TimeField(help_text='Scheduled time for this dose')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Taken', 'Taken'), ('Missed', 'Missed')], default='Pending', max_length=10)),
                ('date', models.DateField(help_text='Date this dose is scheduled')),
                ('marked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose_logs', to='accounts.medicine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'scheduled_time'],
                'indexes': [models.Index(fields=['user', 'date'], name='accounts_me_user_id_3abcf6_idx'), models.Index(fields=['medicine', 'date'], name='accounts_me_medicin_fbd665_idx'), models.Index(fields=['status', 'date'], name='accounts_me_status_a6fc64_idx')],
                'unique_together': {('user', 'medicine', 'scheduled_time', 'date')},
            },
        ),
    ]
