# Generated by Django 5.2.11 on 2026-03-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_medicine_next_due_time_medicinedoselog'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinedoselog',
            name='actual_taken_time',
            field=models.DateTimeField(blank=True, help_text='Actual time when dose was taken', null=True),
        ),
    ]
